version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    # specify the version you desire here
    - image: circleci/node:8.9.1

jobs:
  build:
    <<: *defaults
    branches:
      only:
        - master
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: git config user.name "shiopon01+circleci"
      - run: git config user.email "shio.0323+circleci@gmail.com"
      - run: npm install
      - run: npm run build
      - run: npm run export
      - run: git reset --hard HEAD
      - run: git checkout gh-pages
      - run: rm -rf index.html 404.html _next/
      - run: mv -f src/out/* ./
      - run: git add .
      - run: git commit -m 'update by circleci'
      - run: git push origin gh-pages

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # run tests!
      # - run: yarn test
