version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:9.11

jobs:
  build:
    <<: *defaults
    branches:
      only:
        - master
    steps:
      - checkout
      - run: npm config set prefix '$HOME/.npm-global/'
      - run: npm install -g typesync
      - run: git config user.name "shiopon01+circleci"
      - run: git config user.email "shio.0323+circleci@gmail.com"
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: npm run build
      - run: npm run ci
      - run: git reset --hard HEAD
      - run: git checkout gh-pages
      - run: ls | grep -v -E 'out|CNAME$' | xargs rm -rf
      - run: mv -f out/* ./
      - run: touch .nojekyll
      - run: git add .
      - run: git commit -m 'update by circleci'
      - run: git push origin gh-pages
